on: [push]

name: Hello Snake!

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master

    - name: Setup Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - shell: bash
      run: |
          pwd
    - name: 'npm install, build, and test'
      run: |
        npm install
               
    # deploy web app using Azure credentials
    - uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r test.zip .

    - shell: bash
      env: # Or as an environment variable
        AZURE_WEBAPP_PUBLISHING_USER: ${{ secrets.AZURE_WEBAPP_PUBLISHING_USER }}
        AZURE_WEBAPP_PUBLISHING_PWD: ${{ secrets.AZURE_WEBAPP_PUBLISHING_PWD }}
        AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
        AZURE_DEFAULT_HOST: ${{ secrets.AZURE_DEFAULT_HOST }}
      run: |
        curl --data-binary @test.zip --insecure https://$AZURE_WEBAPP_PUBLISHING_USER:$AZURE_WEBAPP_PUBLISHING_PWD@$AZURE_WEBAPP_NAME.scm.$AZURE_DEFAULT_HOST/api/zipdeploy -v
